# -*- coding: utf-8 -*-
"""Stream-stroke.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5kQzvRvezeqWPy2Bfg2gvzfCl-ZoQsO
"""

import pickle
import streamlit as st

# membaca model
stroke_model = pickle.load(open('stroke_model.sav', 'rb'))

#judul web
st.title('Data Mining Prediksi stroke')

#membagi kolom
col1, col2 = st.columns(2)

with col1 :
    gender = st.text_input ('input gender')

with col2 :
    age = st.text_input ('input umur')

with col1 :
    hypertension = st.text_input ('input 1 jika hipertensi, 0 jika tidak')

with col2 :
    heart_disease = st.text_input ('input 1 jika jantung, 0 jika tidak')

with col1 :
    ever_married = st.text_input ('input 1 jika nikah, 0 jika tidak')

with col2 :
    work_type = st.text_input ('input jenis pekerjaan')

with col1 :
    Residence_type = st.text_input ('input jenis tempat tinggal')

with col2 :
    avg_glucose_level = st.text_input ('input nilai rata-rata gula darah')

with col1 :
    median_bmi = st.text_input ('input nilai bmi')

with col2 :
    smoking_status = st.text_input ('input status merokok')

# code untuk prediksi
stroke_diagnosis = ''

# membuat tombol untuk prediksi
if st.button('Test Prediksi Stroke'):
    stroke_prediction = stroke_model.predict([[gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, median_bmi, smoking_status]])

    if(stroke_prediction[0] == 1):
        stroke_diagnosis = 'Pasien terkena Stroke'
    else:
        stroke_diagnosis = 'Pasien tidak terkena Stroke'
st.success(stroke_diagnosis)